from pathlib import Path
import json,hashlib,subprocess
R=Path(__file__).parent;repo=R.parents[3];downloads=json.loads((R/'downloads.json').read_text())
# Exact bytes remain untouched; text is a separate pdftotext -layout or HTML text derivative.
data={
's4-mk3':('Native Instruments','Traktor Kontrol S4 MK3','protocol-gap','Owner manual describes native Traktor operation, not a MIDI address chart. NI employee MichaelK_NI explicitly confirms S4 MK3 never supported MIDI. Native overmapping is not proof of MIDI mode.',{'addresses':'not available for standard MIDI','channels':'not applicable','layers':'native deck/pad behavior only','encoders':'native behavior only','led_feedback':'native display/lighting only'},['manual.pdf: concepts and hardware reference; full-text MIDI search finds software MIDI clock, not device messages','ni-staff-midi-explanation.html: Accepted answers > MichaelK_NI']),
's3':('Native Instruments','Traktor Kontrol S3','partial','Official support confirms fixed firmware MIDI mode: hold left FLX while connecting, disconnect to exit. Manual lacks control-address chart. NI staff distinguishes fixed firmware messages from Controller Editor configuration.',{},['shared/ni-midi-mode.html: controller model table, S3 row and *** footnote','manual.pdf: hardware and operation sections; full-text MIDI search','s4-mk3/ni-staff-midi-explanation.html: MichaelK_NI accepted answer']),
's2-mk3':('Native Instruments','Traktor Kontrol S2 MK3','partial','Official support confirms fixed firmware MIDI mode: hold left FLX while connecting, disconnect to exit. Manual lacks control-address chart; do not apply S2 MK2 addresses.',{},['shared/ni-midi-mode.html: controller model table, S2 MK3 row and *** footnote','manual.pdf: hardware and operation sections; full-text MIDI search']),
'x1-mk3':('Native Instruments','Traktor X1 MK3','partial','MIDI mode explicitly documented via SHIFT + Mode Select. No numeric address/channel/encoder/LED protocol table found in downloaded manual.',{},['manual.pdf: PDF page 9, printed page 7, section 5 Effect Control > Mode Select Button']),
'z1-mk2':('Native Instruments','Traktor Z1 MK2','partial','Manual confirms MIDI mode via --- + menu buttons. Native four-deck switching does not establish MIDI layer addresses. No complete wire protocol table found.',{},['manual.pdf: PDF page 8, printed page 6, Using the Traktor Z1 MK2 as a MIDI Controller']),
'mx2':('Native Instruments','Traktor MX2','partial','Included because current official product page and downloads identify MX2. MIDI-mode support table says left SHIFT + right SHIFT; manual focuses on native Traktor behavior and has no numeric MIDI chart.',{},['shared/ni-mx2-current.html: product description and Learn Traktor MX2','shared/ni-midi-mode.html: Traktor MX2 row','manual.pdf: printed page 17 Customizing your MX2; full-text MIDI search']),
'f1':('Native Instruments','Traktor Kontrol F1','partial','MIDI mode and configurable Controller Editor behavior documented. Ordinary MIDI requires the MIDI Mode preference; default User Map uses proprietary NHL. Need a pinned/exported Controller Editor template before assigning concrete addresses.',{'addresses':'template-dependent; no single fixed factory address table established','channels':'template-dependent','layers':'Controller Editor pages; User Map is NHL, not MIDI','encoders':'freely assignable encoder turn and push; message modes in editor reference','led_feedback':'RGB pads single/dual/HSB modes and 7-segment Note velocity/CC display described'},['manual.pdf: pp119-121 section 4.12; p128 MIDI Mode preference','controller-editor.pdf: pp162-168 section 14 Using Your Traktor Kontrol F1; pp166-168 LED/display details']),
'djcontrolinpulse500':('Hercules','DJControl Inpulse 500','ready-for-extraction','Detailed official 14-page MIDI chart has Note/CC bytes, Shift and pad modes, relative encoders, paired MSB/LSB tempo and LED colors. Ready means extraction may begin; source anomalies require a review queue.',{'addresses':'numeric decimal and hex input/output tables throughout pp1-14','channels':'chart uses zero-based channel nibble: Deck1 91/B1 = human channel2, shifted 94/B4 = human channel5; do not use printed 1 as human channel1','layers':'Shift changes deck/mixer channel; pads use mode-dependent note ranges, pp2-4 and 12-14','encoders':'p1 Autoloop CC0E relative 7F..40 CCW / 01..3F CW; p2 jog and 14-bit tempo CC08+CC28','led_feedback':'p4/p14 RGB palette and pp7-8 meters/individual LEDs'},['midi.pdf: pp1-14; p1 D1-1 Play 91 07 00/7F; p2 tempo/jog; p14 palette visually inspected','Source anomalies: p2 Centre backlight blank address; jog touch B1 08 overlaps tempo coarse CC08; resolve against hardware/manufacturer before final profile']),
'xone-96':('Allen & Heath','Xone:96','ready-for-extraction','PDF endpoints returned 403, but official full HTML user guide and MIDI implementation tables downloaded successfully. Explicit numeric send/receive matrix supports extraction.',{'addresses':'CH faders CC00..03, crossfader CC05; CUE notes hex00..07; selector matrix hex13..33','channels':'default human channel16; startup setup supports1..16','layers':'no controller latching layers; source-selector switch positions separately enumerated','encoders':'rotary switches are discrete note positions; no relative rotary encoding needed for listed controls','led_feedback':'matrix separates OUT/IN; CUE/filter/on-off receive notes, source/faders do not; NOTE OFF00 / ON7F'},['midi.html: MIDI Control matrix, CH IP SOURCE MIDI VALUES, MIDI Channel Setup, MIDI Implementation Tables','manual.html: MIDI Control; CUE states can be controlled remotely via USB']),
'xone-92-mk2':('Allen & Heath','Xone:92 Mk2','ready-for-extraction','Small, explicit transmit-only implementation: filters CC12/13, crossfader CC92, optional internally configured data CC94. Clock/start-stop exceed current simple Note/CC scope.',{'addresses':'CC12,13,92 and optional94; no notes','channels':'default16; internal option15','layers':'none; CC94 depends on internal jumper','encoders':'no relative encoder messages documented','led_feedback':'not supported: implementation Received column is X throughout'},['manual.pdf: pp23-25 MIDI Control, MIDI Control Codes, MIDI Implementation Chart; p35 installer links; p25 rendered inspection']),
'xone-px5':('Allen & Heath','Xone:PX5','partial','Extensive MIDI controls documented, but note names use C-2 in mapping while conversion table maps zero to C-1. Do not silently normalize conflicting octaves. CC portion is extractable; resolve Note numbers and return-value details first.',{'addresses':'CC0..11 explicit; note-name mapping documented but octave convention conflicts with conversion table','channels':'default16, configurable via FX SELECT CONFIG CHANNEL, retained across power cycles','layers':'switch INT/DUAL/EXT position notes; no latching layers documented','encoders':'FX rotary CC assignments shown; increment/absolute detail needs validation','led_feedback':'send/receive capability stated, but per-control output semantics need confirmation'},['manual.pdf: pp29-34 MIDI CONTROL and MIDI CHANNEL CHANGE; p30 visually inspected','midi.html: Channel FX MODE Select Switches versus Octave/Note Numbers conversion table; CC conversion table also has hex errors at13-15'])}
for key in ['djcontrolinpulset7','djcontrolinpulse300mk2','djcontrolinpulse200mk2','djcontrolinpulse200mk3','djcontrolstarlight']:
 name={'djcontrolinpulset7':'DJControl Inpulse T7 / T7 Premium','djcontrolinpulse300mk2':'DJControl Inpulse 300 MK2','djcontrolinpulse200mk2':'DJControl Inpulse 200 MK2','djcontrolinpulse200mk3':'DJControl Inpulse 200 MK3','djcontrolstarlight':'DJControl Starlight'}[key]
 loc=['support.html: official model support and manuals','manual.pdf: English control descriptions; MIDI keyword inspection']
 if (R/key/'djuced-midi.html').exists():loc+=['djuced-midi.html: Controls > Mixer Controls, Decks Controls, Pads Modes (software action mapping, not wire addresses)']
 if key=='djcontrolinpulset7':loc+=['manual.pdf: PDF page84 / English printed83 MIDI controls test (test procedure, not address table)']
 note='Official user manual/control descriptions archived; no complete manufacturer wire-address/LED chart found in the retrieved support resources. Software action mappings do not prove Note/CC values.'
 if key=='djcontrolinpulse200mk3':note+=' Added as a current-generation supplement discovered on current official support; retained MK2 as explicitly requested legacy model.'
 data[key]=('Hercules',name,'partial',note,{},loc)
for m in ['xone-k1','xone-k2','xone-k3']:
 old=repo/'XtremeMapping/docs/controllers'/m/'source-manifest.json';src=json.loads(old.read_text());d=R/m;d.mkdir(exist_ok=True)
 refs=[]
 for x in src['sources']:
  p=old.parent/x['file'];refs.append(dict(x,file=str(p.relative_to(repo)),existing_archive=True,sha256=hashlib.sha256(p.read_bytes()).hexdigest()))
 if m=='xone-k3':loc=['existing User Guide: MIDI Controls, Global MIDI Channel, Latching Layer Options, MIDI Map, MIDI IMPLEMENTATION DEFAULT Send/Return','Existing original MIDI PNG diagrams retained; no duplicate copies.'];detail='Factory Map(1) matches K2; per-control custom map and global channel choices require separate profile assumptions.'
 else:loc=['existing manual.pdf: '+('pp8,12-15' if m=='xone-k1' else 'pp9,11-19')+' MIDI controls/channel/implementation Send and Return'];detail='Original official PDF already archived; separate extracted text added here for indexing.'
 data[m]=('Allen & Heath',m.replace('xone-','Xone:').upper(),'ready-for-extraction',detail,{'addresses':'existing MIDI send and return diagrams','channels':'default15; configurable','layers':'K1 fixed map; K2/K3 optional three latching layers; distinguish exact model','encoders':'two’s complement relative CC; K3 configurable','led_feedback':'dedicated return diagrams; K1/K2 tri-color, K3 factory return plus editor-custom RGB'},loc)
 manifest={'manufacturer':data[m][0],'model':data[m][1],'grade':data[m][2],'sources':refs,'notes':detail,'coverage':data[m][4],'inspected_locators':loc,'retrieved_on':'2026-09-12','hardware_tested':False,'scope':'Source extraction readiness only; not a verified SXM profile'}
 (d/'manifest.json').write_text(json.dumps(manifest,indent=2,ensure_ascii=False))
for m,(brand,name,grade,note,cov,loc) in data.items():
 if m.startswith('xone-k'):continue
 d=R/m;d.mkdir(exist_ok=True)
 if not cov:cov={k:'not established by retrieved protocol documentation' for k in ['addresses','channels','layers','encoders','led_feedback']}
 sources=[];seen=set()
 for s in downloads:
  if s['file'].split('/')[0]!=m:continue
  if (s['url'],s['file']) in seen:continue
  seen.add((s['url'],s['file']));s=dict(s)
  if 'error' not in s and 'text_file'in s:s['text_sha256']=hashlib.sha256((R/s['text_file']).read_bytes()).hexdigest()
  sources.append(s)
 doc={'manufacturer':brand,'model':name,'retrieved_on':'2026-09-12','grade':grade,'scope':'Source extraction readiness only; not a verified SXM profile','hardware_tested':False,'selection_basis':'Official manufacturer manual/support listing; representative current and explicitly requested legacy models, not sales ranking','notes':note,'coverage':cov,'inspected_locators':loc,'sources':sources,'shared_references':['shared/ni-current-downloads.html','shared/ni-midi-mode.html'] if brand=='Native Instruments' else []}
 (d/'manifest.json').write_text(json.dumps(doc,indent=2,ensure_ascii=False))
lines=['# Native Instruments, Hercules, Allen & Heath source library','', 'Retrieved 2026-09-12. Manufacturer manuals and support sources only. DJUCED is Hercules/Guillemot’s own software site, explicitly linked from Hercules support. NI community evidence is restricted to the named NI employee’s accepted answer; other posts are not evidence. Model selection is representative, not a sales or popularity ranking. MX2 and Inpulse 200 MK3 were verified on current official pages; older requested models remain identified by exact generation.','', 'Grades concern documentation available for extraction, never an app profile or hardware test. Original downloads and SHA-256 values are in each model manifest and downloads.json. PDFs are retained byte-for-byte with layout text derivatives; HTML is retained with text derivatives. Printed page numbers equal PDF page numbers unless stated. Existing K1/K2/K3 sources are referenced without duplicating originals.','', '| Model | Grade | Findings and next work |','|---|---|---|']
for m,(b,n,g,note,c,l) in data.items():lines.append(f'| {b} {n} | {g} | {note} See [{m}/manifest.json]({m}/manifest.json) for exact locators. |')
lines+=['','## Recommended next profile work','','1. Xone:92 Mk2: extract the three default CC controls and identify optional CC94 separately. Exclude realtime clock/start-stop from a simple Note/CC-only profile.','2. Xone:96: extract numeric send/receive matrix using human channel16; preserve USB output enable routing and which controls accept return data.','3. Inpulse 500: extract chart into an intermediate review table, converting zero-based channel nibbles explicitly. Preserve Shift and pad-mode state, paired tempo CCs, relative encoding and LED values. Resolve missing/conflicting rows before promoting any final map.','4. Existing K-series: reuse archived sources and existing app work. K3 factory and custom editor maps must remain distinct; avoid importing K2 layer assumptions into K1.','5. PX5: CC map can progress, but block numeric Note conversion pending official clarification or hardware capture of conflicting octave labels.','6. NI and remaining Hercules: acquire an official protocol/template or capture documented MIDI mode on hardware. Native Traktor behavior and software action tables alone are insufficient. S4 MK3 is excluded from generic MIDI profiling.','','## Limits and retrieval failures','','- Xone:96 owner PDF and separate MIDI PDF returned HTTP403. Official support HTML user guide and full numeric implementation table were retrieved; this is a format fallback, not an inaccessible model. Exact failures remain in downloads.json.','- Large Hercules manuals contain many languages; inspection targets the English controls and any MIDI sections, with full text retained for all pages.','- SXM currently represents simple Note/CC mappings: high-resolution pairs, encoder semantics, LED feedback values, latching layers, mode-dependent addressing, proprietary NHL/native operation and MIDI realtime require explicit modeling or documented exclusions. This archive implements none of those features.','- Inpulse500 table anomalies and PX5 conversion inconsistencies are recorded rather than silently corrected. Hardware was not available/tested.','- Source files are manufacturer copyright; preserved here as research reference material. No redistribution license inferred.']
(R/'group-report.md').write_text('\n'.join(lines)+'\n')
print('models',len(data))
