//
//  CommandHierarchy.swift
//  SuperXtremeMapping
//
//  Created by u/nonomomomo2 on 13/01/2026.
//

import Foundation

/// Represents a category of Traktor commands for hierarchical menu display.
struct CommandCategory2: Identifiable {
    let id = UUID()
    let name: String
    let subcategories: [CommandCategory2]?
    let commands: [CommandItem]?

    init(name: String, subcategories: [CommandCategory2]? = nil, commands: [CommandItem]? = nil) {
        self.name = name
        self.subcategories = subcategories
        self.commands = commands
    }
}

/// A single command item with its ID and display name.
struct CommandItem: Identifiable {
    let id: Int
    let name: String
}

/// Hierarchical organization of Traktor commands for menu display.
enum CommandHierarchy {

    /// Returns the full command hierarchy for menus
    static let categories: [CommandCategory2] = [
        // Mixer
        CommandCategory2(name: "Mixer", subcategories: [
            CommandCategory2(name: "Main", commands: [
                CommandItem(id: 5, name: "X-Fader Position"),
                CommandItem(id: 6, name: "Master Volume"),
                CommandItem(id: 7, name: "Limiter On"),
                CommandItem(id: 8, name: "Monitor Volume"),
                CommandItem(id: 17, name: "Monitor Mix"),
                CommandItem(id: 9, name: "Deck Focus Selector"),
                CommandItem(id: 14, name: "Crossfader Curve"),
                CommandItem(id: 19, name: "Tempo Range Selector"),
                CommandItem(id: 60, name: "Auto Master Mode"),
            ]),
            CommandCategory2(name: "Tempo Master", commands: [
                CommandItem(id: 62, name: "Clock Int/Ext"),
                CommandItem(id: 64, name: "Set Master Tempo"),
                CommandItem(id: 69, name: "Master Tempo Selector"),
                CommandItem(id: 2471, name: "Master Clock Tempo"),
                CommandItem(id: 2472, name: "Master Clock Phase"),
            ]),
            CommandCategory2(name: "Mixer FX", commands: [
                CommandItem(id: 349, name: "Mixer FX Selector"),
                CommandItem(id: 350, name: "Mixer FX On"),
                CommandItem(id: 351, name: "Mixer FX Adjust"),
            ]),
            CommandCategory2(name: "Audio Recorder", commands: [
                CommandItem(id: 29, name: "Audio Recorder Gain"),
                CommandItem(id: 2055, name: "Audio Recorder Cut"),
                CommandItem(id: 2056, name: "Audio Recorder Record/Stop"),
                CommandItem(id: 2057, name: "Broadcasting On"),
                CommandItem(id: 2058, name: "Audio Recorder State"),
                CommandItem(id: 3084, name: "Load Last Recording"),
            ]),
            CommandCategory2(name: "Output Meters", commands: [
                CommandItem(id: 2704, name: "Main Level (L)"),
                CommandItem(id: 2705, name: "Main Level (R)"),
                CommandItem(id: 2706, name: "Booth Level (L)"),
                CommandItem(id: 2707, name: "Booth Level (R)"),
                CommandItem(id: 2708, name: "Monitor Level (L)"),
                CommandItem(id: 2709, name: "Monitor Level (R)"),
                CommandItem(id: 2710, name: "Microphone Level"),
            ]),
        ]),

        // Deck Common
        CommandCategory2(name: "Deck Common", subcategories: [
            CommandCategory2(name: "Transport", commands: [
                CommandItem(id: 100, name: "Play/Pause"),
                CommandItem(id: 101, name: "Play"),
                CommandItem(id: 102, name: "Volume"),
                CommandItem(id: 103, name: "Seek Position"),
                CommandItem(id: 104, name: "Scratch"),
                CommandItem(id: 117, name: "Mixer Gain"),
                CommandItem(id: 118, name: "Auto-Gain"),
                CommandItem(id: 119, name: "Monitor Cue On"),
                CommandItem(id: 127, name: "Balance"),
            ]),
            CommandCategory2(name: "Jog", commands: [
                CommandItem(id: 120, name: "Jog Turn"),
                CommandItem(id: 121, name: "Jog Scratch"),
                CommandItem(id: 2187, name: "Jog Touch On"),
                CommandItem(id: 2188, name: "Jog Mode"),
            ]),
            CommandCategory2(name: "Tempo", commands: [
                CommandItem(id: 122, name: "Tempo Sync"),
                CommandItem(id: 123, name: "Tempo Adjust"),
                CommandItem(id: 124, name: "Phase Sync"),
                CommandItem(id: 125, name: "Sync On"),
                CommandItem(id: 126, name: "Beat Sync"),
                CommandItem(id: 404, name: "Tempo Bend (Stepless)"),
                CommandItem(id: 406, name: "Tempo Bend"),
                CommandItem(id: 2292, name: "Tempo"),
                CommandItem(id: 2293, name: "Set as Tempo Master"),
                CommandItem(id: 2294, name: "Is Tempo Master"),
                CommandItem(id: 2476, name: "Tempo Bend Up"),
                CommandItem(id: 2477, name: "Tempo Bend Down"),
            ]),
            CommandCategory2(name: "Key", commands: [
                CommandItem(id: 400, name: "Keylock On"),
                CommandItem(id: 401, name: "Key Reset"),
                CommandItem(id: 402, name: "Key Adjust"),
                CommandItem(id: 403, name: "Key Match"),
                CommandItem(id: 405, name: "Keylock On (Preserve Pitch)"),
                CommandItem(id: 2291, name: "Is Key Locked"),
            ]),
            CommandCategory2(name: "Grid", commands: [
                CommandItem(id: 2237, name: "Autogrid"),
                CommandItem(id: 2238, name: "BPM Adjust"),
                CommandItem(id: 2239, name: "Grid Adjust"),
                CommandItem(id: 2240, name: "Beat Tap"),
                CommandItem(id: 2241, name: "BPM Lock On"),
                CommandItem(id: 2242, name: "Gridlock On"),
                CommandItem(id: 2248, name: "Set Grid Marker"),
                CommandItem(id: 2249, name: "Delete Grid Marker"),
                CommandItem(id: 2250, name: "Grid Marker Position"),
                CommandItem(id: 2251, name: "Beat Phase"),
                CommandItem(id: 2252, name: "Tick On"),
                CommandItem(id: 2253, name: "Move Grid Marker"),
                CommandItem(id: 2254, name: "Reset BPM"),
                CommandItem(id: 2255, name: "Copy Phase from Tempo Master"),
                CommandItem(id: 2256, name: "Detected BPM"),
                CommandItem(id: 2257, name: "Track BPM"),
                CommandItem(id: 2258, name: "BPM x2"),
                CommandItem(id: 2259, name: "BPM /2"),
                CommandItem(id: 2810, name: "Downbeat"),
                CommandItem(id: 2811, name: "Reset Downbeat"),
            ]),
            CommandCategory2(name: "Load", commands: [
                CommandItem(id: 2176, name: "Load Next"),
                CommandItem(id: 2177, name: "Load Previous"),
                CommandItem(id: 2178, name: "Unload Deck"),
                CommandItem(id: 2180, name: "Load Selected"),
                CommandItem(id: 2394, name: "Load"),
                CommandItem(id: 2395, name: "Load, Loop and Play"),
                CommandItem(id: 2401, name: "Duplicate Track Deck A"),
                CommandItem(id: 2402, name: "Duplicate Track Deck B"),
                CommandItem(id: 2403, name: "Duplicate Track Deck C"),
                CommandItem(id: 2404, name: "Duplicate Track Deck D"),
            ]),
            CommandCategory2(name: "Status", commands: [
                CommandItem(id: 2295, name: "Elapsed Time"),
                CommandItem(id: 2296, name: "Remaining Time"),
                CommandItem(id: 2297, name: "Next Cue Position"),
                CommandItem(id: 2303, name: "Deck Type"),
                CommandItem(id: 2304, name: "Track Length"),
                CommandItem(id: 2589, name: "Is Playing"),
                CommandItem(id: 2590, name: "Is Synced"),
                CommandItem(id: 2591, name: "Deck Is Loaded"),
            ]),
            CommandCategory2(name: "Track Info", commands: [
                CommandItem(id: 2592, name: "Track Title"),
                CommandItem(id: 2593, name: "Track Artist"),
                CommandItem(id: 2594, name: "Track Album"),
                CommandItem(id: 2595, name: "Track Genre"),
                CommandItem(id: 2596, name: "Track Comment"),
                CommandItem(id: 2597, name: "Track Key"),
                CommandItem(id: 2598, name: "Track Rating"),
            ]),
            CommandCategory2(name: "Meters", commands: [
                CommandItem(id: 2688, name: "Deck A Pre-Fader Level (L)"),
                CommandItem(id: 2689, name: "Deck B Pre-Fader Level (L)"),
                CommandItem(id: 2690, name: "Deck C Pre-Fader Level (L)"),
                CommandItem(id: 2691, name: "Deck D Pre-Fader Level (L)"),
                CommandItem(id: 2692, name: "Deck A Pre-Fader Level (R)"),
                CommandItem(id: 2693, name: "Deck B Pre-Fader Level (R)"),
                CommandItem(id: 2694, name: "Deck C Pre-Fader Level (R)"),
                CommandItem(id: 2695, name: "Deck D Pre-Fader Level (R)"),
                CommandItem(id: 2696, name: "Deck A Post-Fader Level (L)"),
                CommandItem(id: 2697, name: "Deck B Post-Fader Level (L)"),
                CommandItem(id: 2698, name: "Deck C Post-Fader Level (L)"),
                CommandItem(id: 2699, name: "Deck D Post-Fader Level (L)"),
                CommandItem(id: 2700, name: "Deck A Post-Fader Level (R)"),
                CommandItem(id: 2701, name: "Deck B Post-Fader Level (R)"),
                CommandItem(id: 2702, name: "Deck C Post-Fader Level (R)"),
                CommandItem(id: 2703, name: "Deck D Post-Fader Level (R)"),
            ]),
        ]),

        // Cue & Loop
        CommandCategory2(name: "Cue / Loop", subcategories: [
            CommandCategory2(name: "Cue", commands: [
                CommandItem(id: 206, name: "Cue"),
                CommandItem(id: 204, name: "CUP (Cue Play)"),
                CommandItem(id: 205, name: "Cup (Cue Play & Pause)"),
                CommandItem(id: 207, name: "Cue/Play"),
                CommandItem(id: 208, name: "Cue/Pause"),
                CommandItem(id: 209, name: "Cue/Set+Store"),
                CommandItem(id: 213, name: "Set Cue & Store as Next Hotcue"),
                CommandItem(id: 2392, name: "Loop In / Set Cue"),
            ]),
            CommandCategory2(name: "Loop", commands: [
                CommandItem(id: 200, name: "Loop In"),
                CommandItem(id: 201, name: "Loop Out"),
                CommandItem(id: 202, name: "Loop Active On"),
                CommandItem(id: 203, name: "Reloop"),
                CommandItem(id: 2192, name: "Loop Set"),
                CommandItem(id: 2193, name: "Loop Size"),
                CommandItem(id: 2194, name: "Loop Size +1"),
                CommandItem(id: 2195, name: "Loop Size -1"),
                CommandItem(id: 2196, name: "Loop Size Selector"),
                CommandItem(id: 2197, name: "Loop Move Forward"),
                CommandItem(id: 2198, name: "Loop Move Backward"),
                CommandItem(id: 2316, name: "Loop Active"),
                CommandItem(id: 2317, name: "Loop Size Select+Set"),
                CommandItem(id: 2318, name: "Backward Loop Size Select+Set"),
                CommandItem(id: 2319, name: "Current Loop Size"),
                CommandItem(id: 2393, name: "Loop Out"),
            ]),
            CommandCategory2(name: "Hotcue", commands: [
                CommandItem(id: 214, name: "Hotcue 1"),
                CommandItem(id: 215, name: "Hotcue 2"),
                CommandItem(id: 216, name: "Hotcue 3"),
                CommandItem(id: 217, name: "Hotcue 4"),
                CommandItem(id: 218, name: "Hotcue 5"),
                CommandItem(id: 219, name: "Hotcue 6"),
                CommandItem(id: 220, name: "Hotcue 7"),
                CommandItem(id: 221, name: "Hotcue 8"),
                CommandItem(id: 2306, name: "Jump to Next/Prev Cue/Loop"),
                CommandItem(id: 2307, name: "Active Cue/Loop"),
                CommandItem(id: 2308, name: "Store Floating Cue/Loop as Next Hotcue"),
                CommandItem(id: 2309, name: "Delete Current Hotcue"),
                CommandItem(id: 2310, name: "Active Hotcue Index"),
                CommandItem(id: 2314, name: "Hotcue Type"),
                CommandItem(id: 2315, name: "Map Hotcue"),
                CommandItem(id: 2327, name: "Cue Type Selector"),
                CommandItem(id: 2328, name: "Select/Set+Store Hotcue"),
                CommandItem(id: 2329, name: "Hotcue State"),
                CommandItem(id: 2330, name: "Total Hotcues"),
                CommandItem(id: 2331, name: "Delete Hotcue"),
            ]),
            CommandCategory2(name: "Move & Beatjump", commands: [
                CommandItem(id: 2351, name: "Move"),
                CommandItem(id: 2352, name: "Move Forward"),
                CommandItem(id: 2353, name: "Move Backward"),
                CommandItem(id: 2372, name: "Move Size Selector"),
                CommandItem(id: 2380, name: "Beatjump"),
                CommandItem(id: 2381, name: "Beatjump Forward"),
                CommandItem(id: 2382, name: "Beatjump Backward"),
                CommandItem(id: 2391, name: "Move Mode Selector"),
            ]),
            CommandCategory2(name: "Misc", commands: [
                CommandItem(id: 210, name: "Preview Play/Pause"),
                CommandItem(id: 211, name: "Preview Seek Position"),
                CommandItem(id: 212, name: "Preview Load Selected"),
                CommandItem(id: 229, name: "Quantize Selector"),
                CommandItem(id: 230, name: "Quantize On (Remix)"),
                CommandItem(id: 2311, name: "Snap On"),
                CommandItem(id: 2312, name: "Quant On"),
                CommandItem(id: 2313, name: "Quant On (Global)"),
                CommandItem(id: 2350, name: "Flux Mode On"),
            ]),
        ]),

        // EQ
        CommandCategory2(name: "EQ", commands: [
            CommandItem(id: 301, name: "EQ Low"),
            CommandItem(id: 302, name: "EQ Mid"),
            CommandItem(id: 303, name: "EQ High"),
            CommandItem(id: 316, name: "EQ Mid-Low"),
            CommandItem(id: 304, name: "EQ Low Kill"),
            CommandItem(id: 305, name: "EQ Mid Kill"),
            CommandItem(id: 306, name: "EQ High Kill"),
            CommandItem(id: 307, name: "EQ Mid-Low Kill"),
            CommandItem(id: 308, name: "EQ Low Reset"),
            CommandItem(id: 309, name: "EQ Mid Reset"),
            CommandItem(id: 310, name: "EQ High Reset"),
        ]),

        // Filter
        CommandCategory2(name: "Filter", commands: [
            CommandItem(id: 320, name: "Filter"),
            CommandItem(id: 319, name: "Filter On"),
        ]),

        // FX
        CommandCategory2(name: "FX", subcategories: [
            CommandCategory2(name: "FX Unit", commands: [
                CommandItem(id: 369, name: "FX Unit On"),
                CommandItem(id: 365, name: "FX Dry/Wet"),
                CommandItem(id: 366, name: "FX Knob 1"),
                CommandItem(id: 367, name: "FX Knob 2"),
                CommandItem(id: 368, name: "FX Knob 3"),
                CommandItem(id: 370, name: "FX Button 1"),
                CommandItem(id: 371, name: "FX Button 2"),
                CommandItem(id: 372, name: "FX Button 3"),
                CommandItem(id: 362, name: "Effect 1 Selector"),
                CommandItem(id: 363, name: "Effect 2 Selector"),
                CommandItem(id: 364, name: "Effect 3 Selector"),
                CommandItem(id: 2301, name: "FX Unit Mode Selector"),
                CommandItem(id: 324, name: "FX Single Mode"),
                CommandItem(id: 326, name: "FX Store Preset"),
                CommandItem(id: 327, name: "FX Snapshot"),
                CommandItem(id: 373, name: "FX Snapshot 1"),
                CommandItem(id: 374, name: "FX Snapshot 2"),
                CommandItem(id: 375, name: "FX Reset"),
                CommandItem(id: 323, name: "Effect LFO Reset"),
            ]),
            CommandCategory2(name: "FX Assign", commands: [
                CommandItem(id: 321, name: "FX Unit 1 On"),
                CommandItem(id: 322, name: "FX Unit 2 On"),
                CommandItem(id: 338, name: "FX Unit 3 On"),
                CommandItem(id: 339, name: "FX Unit 4 On"),
                CommandItem(id: 348, name: "Deck Effect On"),
                CommandItem(id: 325, name: "FX Routing Selector"),
            ]),
            CommandCategory2(name: "FX Meters", commands: [
                CommandItem(id: 2711, name: "FX Unit 1 Level"),
                CommandItem(id: 2712, name: "FX Unit 2 Level"),
                CommandItem(id: 2713, name: "FX Unit 3 Level"),
                CommandItem(id: 2714, name: "FX Unit 4 Level"),
            ]),
        ]),

        // Remix Deck
        CommandCategory2(name: "Remix Deck", subcategories: [
            CommandCategory2(name: "Slot Controls", commands: [
                CommandItem(id: 251, name: "Slot Volume"),
                CommandItem(id: 252, name: "Slot Gain"),
                CommandItem(id: 249, name: "Slot Filter Adjust"),
                CommandItem(id: 250, name: "Slot Filter On"),
                CommandItem(id: 248, name: "Slot Pitch Adjust"),
                CommandItem(id: 269, name: "Slot Pitch Reset"),
                CommandItem(id: 237, name: "Slot Keylock On"),
                CommandItem(id: 238, name: "Slot Monitor On"),
                CommandItem(id: 239, name: "Slot FX On"),
                CommandItem(id: 240, name: "Slot Reverse On"),
                CommandItem(id: 259, name: "Slot Mute On"),
                CommandItem(id: 235, name: "Slot Punch On"),
                CommandItem(id: 265, name: "Slot Play Mode"),
                CommandItem(id: 253, name: "All Slots Volume"),
                CommandItem(id: 262, name: "Slot Color"),
                CommandItem(id: 261, name: "Slot BPM Sync"),
            ]),
            CommandCategory2(name: "Slot Size", commands: [
                CommandItem(id: 2000, name: "Slot Size Adjust"),
                CommandItem(id: 2001, name: "Slot Size"),
                CommandItem(id: 266, name: "Slot Size x2"),
                CommandItem(id: 267, name: "Slot Size /2"),
                CommandItem(id: 268, name: "Slot Size Reset"),
            ]),
            CommandCategory2(name: "Playback", commands: [
                CommandItem(id: 241, name: "Remix Deck Play"),
                CommandItem(id: 255, name: "Play All Slots"),
                CommandItem(id: 256, name: "Trigger All Slots"),
                CommandItem(id: 257, name: "Slot Trigger"),
                CommandItem(id: 258, name: "Slot Retrigger Play"),
                CommandItem(id: 260, name: "Slot Retrigger"),
                CommandItem(id: 242, name: "Play Mode All Slots"),
                CommandItem(id: 243, name: "Stop All Slots"),
                CommandItem(id: 254, name: "Delete All Slots"),
            ]),
            CommandCategory2(name: "Load & Capture", commands: [
                CommandItem(id: 233, name: "Load Set from List"),
                CommandItem(id: 234, name: "Save Remix Set"),
                CommandItem(id: 244, name: "Slot Load from List"),
                CommandItem(id: 245, name: "Slot Capture from Deck"),
                CommandItem(id: 263, name: "Slot Capture from Loop Recorder"),
                CommandItem(id: 264, name: "Slot Copy from Slot"),
                CommandItem(id: 246, name: "Slot Unload"),
                CommandItem(id: 2002, name: "Capture Source Selector"),
                CommandItem(id: 2003, name: "Slot Trigger Type"),
            ]),
            CommandCategory2(name: "Cell Triggers (Slot 1)", commands: [
                CommandItem(id: 601, name: "Slot 1 Cell 1 Trigger"),
                CommandItem(id: 602, name: "Slot 1 Cell 2 Trigger"),
                CommandItem(id: 603, name: "Slot 1 Cell 3 Trigger"),
                CommandItem(id: 604, name: "Slot 1 Cell 4 Trigger"),
                CommandItem(id: 605, name: "Slot 1 Cell 5 Trigger"),
                CommandItem(id: 606, name: "Slot 1 Cell 6 Trigger"),
                CommandItem(id: 607, name: "Slot 1 Cell 7 Trigger"),
                CommandItem(id: 608, name: "Slot 1 Cell 8 Trigger"),
                CommandItem(id: 609, name: "Slot 1 Cell 9 Trigger"),
                CommandItem(id: 610, name: "Slot 1 Cell 10 Trigger"),
                CommandItem(id: 611, name: "Slot 1 Cell 11 Trigger"),
                CommandItem(id: 612, name: "Slot 1 Cell 12 Trigger"),
                CommandItem(id: 613, name: "Slot 1 Cell 13 Trigger"),
                CommandItem(id: 614, name: "Slot 1 Cell 14 Trigger"),
                CommandItem(id: 615, name: "Slot 1 Cell 15 Trigger"),
                CommandItem(id: 616, name: "Slot 1 Cell 16 Trigger"),
            ]),
            CommandCategory2(name: "Cell Triggers (Slot 2)", commands: [
                CommandItem(id: 617, name: "Slot 2 Cell 1 Trigger"),
                CommandItem(id: 618, name: "Slot 2 Cell 2 Trigger"),
                CommandItem(id: 619, name: "Slot 2 Cell 3 Trigger"),
                CommandItem(id: 620, name: "Slot 2 Cell 4 Trigger"),
                CommandItem(id: 621, name: "Slot 2 Cell 5 Trigger"),
                CommandItem(id: 622, name: "Slot 2 Cell 6 Trigger"),
                CommandItem(id: 623, name: "Slot 2 Cell 7 Trigger"),
                CommandItem(id: 624, name: "Slot 2 Cell 8 Trigger"),
                CommandItem(id: 625, name: "Slot 2 Cell 9 Trigger"),
                CommandItem(id: 626, name: "Slot 2 Cell 10 Trigger"),
                CommandItem(id: 627, name: "Slot 2 Cell 11 Trigger"),
                CommandItem(id: 628, name: "Slot 2 Cell 12 Trigger"),
                CommandItem(id: 629, name: "Slot 2 Cell 13 Trigger"),
                CommandItem(id: 630, name: "Slot 2 Cell 14 Trigger"),
                CommandItem(id: 631, name: "Slot 2 Cell 15 Trigger"),
                CommandItem(id: 632, name: "Slot 2 Cell 16 Trigger"),
            ]),
            CommandCategory2(name: "Cell Triggers (Slot 3)", commands: [
                CommandItem(id: 633, name: "Slot 3 Cell 1 Trigger"),
                CommandItem(id: 634, name: "Slot 3 Cell 2 Trigger"),
                CommandItem(id: 635, name: "Slot 3 Cell 3 Trigger"),
                CommandItem(id: 636, name: "Slot 3 Cell 4 Trigger"),
                CommandItem(id: 637, name: "Slot 3 Cell 5 Trigger"),
                CommandItem(id: 638, name: "Slot 3 Cell 6 Trigger"),
                CommandItem(id: 639, name: "Slot 3 Cell 7 Trigger"),
                CommandItem(id: 640, name: "Slot 3 Cell 8 Trigger"),
                CommandItem(id: 641, name: "Slot 3 Cell 9 Trigger"),
                CommandItem(id: 642, name: "Slot 3 Cell 10 Trigger"),
                CommandItem(id: 643, name: "Slot 3 Cell 11 Trigger"),
                CommandItem(id: 644, name: "Slot 3 Cell 12 Trigger"),
                CommandItem(id: 645, name: "Slot 3 Cell 13 Trigger"),
                CommandItem(id: 646, name: "Slot 3 Cell 14 Trigger"),
                CommandItem(id: 647, name: "Slot 3 Cell 15 Trigger"),
                CommandItem(id: 648, name: "Slot 3 Cell 16 Trigger"),
            ]),
            CommandCategory2(name: "Cell Triggers (Slot 4)", commands: [
                CommandItem(id: 649, name: "Slot 4 Cell 1 Trigger"),
                CommandItem(id: 650, name: "Slot 4 Cell 2 Trigger"),
                CommandItem(id: 651, name: "Slot 4 Cell 3 Trigger"),
                CommandItem(id: 652, name: "Slot 4 Cell 4 Trigger"),
                CommandItem(id: 653, name: "Slot 4 Cell 5 Trigger"),
                CommandItem(id: 654, name: "Slot 4 Cell 6 Trigger"),
                CommandItem(id: 655, name: "Slot 4 Cell 7 Trigger"),
                CommandItem(id: 656, name: "Slot 4 Cell 8 Trigger"),
                CommandItem(id: 657, name: "Slot 4 Cell 9 Trigger"),
                CommandItem(id: 658, name: "Slot 4 Cell 10 Trigger"),
                CommandItem(id: 659, name: "Slot 4 Cell 11 Trigger"),
                CommandItem(id: 660, name: "Slot 4 Cell 12 Trigger"),
                CommandItem(id: 661, name: "Slot 4 Cell 13 Trigger"),
                CommandItem(id: 662, name: "Slot 4 Cell 14 Trigger"),
                CommandItem(id: 663, name: "Slot 4 Cell 15 Trigger"),
                CommandItem(id: 664, name: "Slot 4 Cell 16 Trigger"),
            ]),
            CommandCategory2(name: "Cell States (Slot 1)", commands: [
                CommandItem(id: 665, name: "Slot 1 Cell 1 State"),
                CommandItem(id: 666, name: "Slot 1 Cell 2 State"),
                CommandItem(id: 667, name: "Slot 1 Cell 3 State"),
                CommandItem(id: 668, name: "Slot 1 Cell 4 State"),
                CommandItem(id: 669, name: "Slot 1 Cell 5 State"),
                CommandItem(id: 670, name: "Slot 1 Cell 6 State"),
                CommandItem(id: 671, name: "Slot 1 Cell 7 State"),
                CommandItem(id: 672, name: "Slot 1 Cell 8 State"),
                CommandItem(id: 673, name: "Slot 1 Cell 9 State"),
                CommandItem(id: 674, name: "Slot 1 Cell 10 State"),
                CommandItem(id: 675, name: "Slot 1 Cell 11 State"),
                CommandItem(id: 676, name: "Slot 1 Cell 12 State"),
                CommandItem(id: 677, name: "Slot 1 Cell 13 State"),
                CommandItem(id: 678, name: "Slot 1 Cell 14 State"),
                CommandItem(id: 679, name: "Slot 1 Cell 15 State"),
                CommandItem(id: 680, name: "Slot 1 Cell 16 State"),
            ]),
            CommandCategory2(name: "Cell States (Slot 2)", commands: [
                CommandItem(id: 681, name: "Slot 2 Cell 1 State"),
                CommandItem(id: 682, name: "Slot 2 Cell 2 State"),
                CommandItem(id: 683, name: "Slot 2 Cell 3 State"),
                CommandItem(id: 684, name: "Slot 2 Cell 4 State"),
                CommandItem(id: 685, name: "Slot 2 Cell 5 State"),
                CommandItem(id: 686, name: "Slot 2 Cell 6 State"),
                CommandItem(id: 687, name: "Slot 2 Cell 7 State"),
                CommandItem(id: 688, name: "Slot 2 Cell 8 State"),
                CommandItem(id: 689, name: "Slot 2 Cell 9 State"),
                CommandItem(id: 690, name: "Slot 2 Cell 10 State"),
                CommandItem(id: 691, name: "Slot 2 Cell 11 State"),
                CommandItem(id: 692, name: "Slot 2 Cell 12 State"),
                CommandItem(id: 693, name: "Slot 2 Cell 13 State"),
                CommandItem(id: 694, name: "Slot 2 Cell 14 State"),
                CommandItem(id: 695, name: "Slot 2 Cell 15 State"),
                CommandItem(id: 696, name: "Slot 2 Cell 16 State"),
            ]),
            CommandCategory2(name: "Cell States (Slot 3)", commands: [
                CommandItem(id: 697, name: "Slot 3 Cell 1 State"),
                CommandItem(id: 698, name: "Slot 3 Cell 2 State"),
                CommandItem(id: 699, name: "Slot 3 Cell 3 State"),
                CommandItem(id: 700, name: "Slot 3 Cell 4 State"),
                CommandItem(id: 701, name: "Slot 3 Cell 5 State"),
                CommandItem(id: 702, name: "Slot 3 Cell 6 State"),
                CommandItem(id: 703, name: "Slot 3 Cell 7 State"),
                CommandItem(id: 704, name: "Slot 3 Cell 8 State"),
                CommandItem(id: 705, name: "Slot 3 Cell 9 State"),
                CommandItem(id: 706, name: "Slot 3 Cell 10 State"),
                CommandItem(id: 707, name: "Slot 3 Cell 11 State"),
                CommandItem(id: 708, name: "Slot 3 Cell 12 State"),
                CommandItem(id: 709, name: "Slot 3 Cell 13 State"),
                CommandItem(id: 710, name: "Slot 3 Cell 14 State"),
                CommandItem(id: 711, name: "Slot 3 Cell 15 State"),
                CommandItem(id: 712, name: "Slot 3 Cell 16 State"),
            ]),
            CommandCategory2(name: "Cell States (Slot 4)", commands: [
                CommandItem(id: 713, name: "Slot 4 Cell 1 State"),
                CommandItem(id: 714, name: "Slot 4 Cell 2 State"),
                CommandItem(id: 715, name: "Slot 4 Cell 3 State"),
                CommandItem(id: 716, name: "Slot 4 Cell 4 State"),
                CommandItem(id: 717, name: "Slot 4 Cell 5 State"),
                CommandItem(id: 718, name: "Slot 4 Cell 6 State"),
                CommandItem(id: 719, name: "Slot 4 Cell 7 State"),
                CommandItem(id: 720, name: "Slot 4 Cell 8 State"),
                CommandItem(id: 721, name: "Slot 4 Cell 9 State"),
                CommandItem(id: 722, name: "Slot 4 Cell 10 State"),
                CommandItem(id: 723, name: "Slot 4 Cell 11 State"),
                CommandItem(id: 724, name: "Slot 4 Cell 12 State"),
                CommandItem(id: 725, name: "Slot 4 Cell 13 State"),
                CommandItem(id: 726, name: "Slot 4 Cell 14 State"),
                CommandItem(id: 727, name: "Slot 4 Cell 15 State"),
                CommandItem(id: 728, name: "Slot 4 Cell 16 State"),
            ]),
            CommandCategory2(name: "Cell Modifiers", commands: [
                CommandItem(id: 729, name: "Cell Load Modifier"),
                CommandItem(id: 730, name: "Cell Delete Modifier"),
                CommandItem(id: 731, name: "Cell Reverse Modifier"),
                CommandItem(id: 732, name: "Cell Capture Modifier"),
                CommandItem(id: 733, name: "Sample Page Selector"),
            ]),
            CommandCategory2(name: "State & Status", commands: [
                CommandItem(id: 247, name: "Slot State"),
                CommandItem(id: 236, name: "Slot Stop/Delete/Load"),
                CommandItem(id: 2004, name: "Slot Capture/Trigger/Mute"),
            ]),
        ]),

        // Step Sequencer
        CommandCategory2(name: "Step Sequencer", commands: [
            CommandItem(id: 734, name: "Step Sequencer On"),
            CommandItem(id: 735, name: "Step Sequencer Swing Amount"),
            CommandItem(id: 736, name: "Step Sequencer Pattern Length"),
            CommandItem(id: 737, name: "Step Sequencer Current Step"),
            CommandItem(id: 738, name: "Step Sequencer Selected Sound"),
            CommandItem(id: 739, name: "Step Sequencer Selected Pattern"),
        ]),

        // Loop Recorder
        CommandCategory2(name: "Loop Recorder", commands: [
            CommandItem(id: 280, name: "Loop Recorder Record"),
            CommandItem(id: 281, name: "Loop Recorder Size"),
            CommandItem(id: 282, name: "Loop Recorder Dry/Wet"),
            CommandItem(id: 283, name: "Loop Recorder Play/Pause"),
            CommandItem(id: 284, name: "Loop Recorder Delete"),
            CommandItem(id: 285, name: "Loop Recorder Overdub On"),
            CommandItem(id: 286, name: "Loop Recorder State"),
            CommandItem(id: 287, name: "Undo/Redo"),
        ]),

        // Browser
        CommandCategory2(name: "Browser", subcategories: [
            CommandCategory2(name: "List", commands: [
                CommandItem(id: 3200, name: "Browser Select Up/Down"),
                CommandItem(id: 3201, name: "Browser Select Page Up/Down"),
                CommandItem(id: 3202, name: "Browser Select Top/Bottom"),
                CommandItem(id: 3203, name: "Browser Select Extend Up/Down"),
                CommandItem(id: 3204, name: "Browser Select Extend Page Up/Down"),
                CommandItem(id: 3205, name: "Browser Select Extend Top/Bottom"),
                CommandItem(id: 3206, name: "Browser Select All"),
                CommandItem(id: 3207, name: "Browser Scroll"),
                CommandItem(id: 3208, name: "Browser Select"),
                CommandItem(id: 3209, name: "Browser Deselect All"),
                CommandItem(id: 3210, name: "Browser Open"),
            ]),
            CommandCategory2(name: "Actions", commands: [
                CommandItem(id: 3211, name: "Browser Delete"),
                CommandItem(id: 3212, name: "Browser Reset Played State"),
                CommandItem(id: 3213, name: "Browser Analyze"),
                CommandItem(id: 3214, name: "Save Collection"),
                CommandItem(id: 3215, name: "Browser Edit"),
                CommandItem(id: 3216, name: "Browser Relocate"),
                CommandItem(id: 3217, name: "Add as Track to Collection"),
                CommandItem(id: 3218, name: "Remove from Collection"),
                CommandItem(id: 3219, name: "Add to Playlist"),
                CommandItem(id: 3220, name: "Remove from Playlist"),
                CommandItem(id: 3223, name: "Expand Remix Set"),
                CommandItem(id: 3224, name: "Browser Clear"),
                CommandItem(id: 3225, name: "Sort by Column"),
                CommandItem(id: 3231, name: "Browser Analysis Lock"),
                CommandItem(id: 3232, name: "Browser Analysis Unlock"),
                CommandItem(id: 3233, name: "Refresh Explorer Folder"),
            ]),
            CommandCategory2(name: "Search", commands: [
                CommandItem(id: 3221, name: "Browser Search"),
                CommandItem(id: 3222, name: "Browser Search Clear"),
                CommandItem(id: 3357, name: "Search in Playlists"),
            ]),
            CommandCategory2(name: "Tree", commands: [
                CommandItem(id: 3328, name: "Browser Tree Select Up/Down"),
                CommandItem(id: 3329, name: "Browser Tree Expand/Collapse"),
                CommandItem(id: 3330, name: "Browser Tree Scroll"),
                CommandItem(id: 3336, name: "Browser Tree Delete"),
                CommandItem(id: 3337, name: "Browser Tree Reset Played State"),
                CommandItem(id: 3338, name: "Browser Tree Analyze"),
                CommandItem(id: 3339, name: "Browser Tree Edit"),
                CommandItem(id: 3340, name: "Browser Tree Relocate"),
                CommandItem(id: 3358, name: "Show in Explorer"),
                CommandItem(id: 3366, name: "Jump to Current Track"),
                CommandItem(id: 3477, name: "Browser Tree Analysis Lock"),
                CommandItem(id: 3478, name: "Browser Tree Analysis Unlock"),
            ]),
            CommandCategory2(name: "Favorites", commands: [
                CommandItem(id: 3456, name: "Favorites Selector"),
                CommandItem(id: 3457, name: "Add Folder to Favorites"),
                CommandItem(id: 3458, name: "Add Folder to Music Folders"),
                CommandItem(id: 3459, name: "Remove from Favorites"),
                CommandItem(id: 3460, name: "Append to Preparation List"),
                CommandItem(id: 3461, name: "Add as Next to Preparation List"),
                CommandItem(id: 3462, name: "Clear Preparation List"),
                CommandItem(id: 3476, name: "Preparation List Count"),
                CommandItem(id: 3480, name: "Add/Remove from Preparation List"),
            ]),
            CommandCategory2(name: "Playlists", commands: [
                CommandItem(id: 3345, name: "Import Music Folders"),
                CommandItem(id: 3346, name: "Export"),
                CommandItem(id: 3347, name: "Export NML"),
                CommandItem(id: 3348, name: "Export Printable"),
                CommandItem(id: 3349, name: "Rename Playlist or Folder"),
                CommandItem(id: 3353, name: "Import Collection"),
                CommandItem(id: 3354, name: "Import Playlist"),
                CommandItem(id: 3367, name: "Restore Auto Gain"),
                CommandItem(id: 3373, name: "Create Playlist"),
                CommandItem(id: 3374, name: "Delete Playlist"),
                CommandItem(id: 3375, name: "Create Playlist Folder"),
                CommandItem(id: 3376, name: "Delete Playlist Folder"),
            ]),
            CommandCategory2(name: "Samples", commands: [
                CommandItem(id: 3469, name: "Add as Loop to Collection"),
                CommandItem(id: 3470, name: "Add as One-Shot Sample to Collection"),
                CommandItem(id: 3471, name: "Remove Sample from Collection"),
                CommandItem(id: 3472, name: "Set to Track"),
                CommandItem(id: 3473, name: "Set to Looped Sample"),
                CommandItem(id: 3474, name: "Set to One-Shot Sample"),
                CommandItem(id: 3475, name: "Export as Remix Set"),
            ]),
        ]),

        // Global
        CommandCategory2(name: "Global", subcategories: [
            CommandCategory2(name: "Clock", commands: [
                CommandItem(id: 2468, name: "Clock Send"),
                CommandItem(id: 2469, name: "Master Clock Beat Tap"),
                CommandItem(id: 2470, name: "Master Clock Tick On"),
                CommandItem(id: 2473, name: "Clock Trigger MIDI Sync"),
                CommandItem(id: 2474, name: "Clock Receive"),
                CommandItem(id: 2475, name: "Clock Tempo Adjust"),
            ]),
            CommandCategory2(name: "Deck Assignment", commands: [
                CommandItem(id: 2408, name: "Assign Left"),
                CommandItem(id: 2409, name: "Assign Right"),
                CommandItem(id: 2410, name: "X-Fader Assign"),
                CommandItem(id: 2113, name: "Auto X-Fade Left"),
                CommandItem(id: 2114, name: "Auto X-Fade Right"),
            ]),
            CommandCategory2(name: "View", commands: [
                CommandItem(id: 4162, name: "Waveform Zoom"),
                CommandItem(id: 4163, name: "DAW View"),
                CommandItem(id: 4208, name: "Layout Selector"),
                CommandItem(id: 4209, name: "Only Browser On"),
                CommandItem(id: 4210, name: "Fullscreen On"),
                CommandItem(id: 4211, name: "Tooltips On"),
                CommandItem(id: 4212, name: "Mixer View"),
                CommandItem(id: 4213, name: "Effect View"),
                CommandItem(id: 4214, name: "Master View"),
                CommandItem(id: 4215, name: "Deck View"),
                CommandItem(id: 4216, name: "Browser View"),
                CommandItem(id: 2298, name: "Advanced Panel Tab Selector"),
                CommandItem(id: 2299, name: "Advanced Panel Toggle"),
                CommandItem(id: 2300, name: "Deck Size Selector"),
                CommandItem(id: 2302, name: "Deck Flavor Selector"),
                CommandItem(id: 2305, name: "Platter/Scope View Selector"),
                CommandItem(id: 2588, name: "Toggle Last Focus"),
                CommandItem(id: 2748, name: "Show Slider Values On"),
                CommandItem(id: 2807, name: "Auto-Gain View On"),
                CommandItem(id: 2808, name: "Stripe View"),
                CommandItem(id: 2809, name: "Phase Meter View"),
            ]),
            CommandCategory2(name: "Timecode", commands: [
                CommandItem(id: 5129, name: "Playback Mode Int/Rel/Abs"),
                CommandItem(id: 5144, name: "Calibrate"),
                CommandItem(id: 5154, name: "Reset Tempo Offset"),
                CommandItem(id: 5155, name: "Timecode Input"),
                CommandItem(id: 5156, name: "Timecode Input State"),
                CommandItem(id: 2288, name: "Scratch Control On"),
                CommandItem(id: 2289, name: "Timecode Tracking"),
                CommandItem(id: 2290, name: "Timecode Quality"),
                CommandItem(id: 3076, name: "Load Selected (Timecode)"),
            ]),
            CommandCategory2(name: "System", commands: [
                CommandItem(id: 3072, name: "Save Traktor Settings"),
                CommandItem(id: 3077, name: "Check Consistency"),
                CommandItem(id: 3137, name: "Load Selected (Preview)"),
                CommandItem(id: 3138, name: "Preview Player State"),
                CommandItem(id: 3139, name: "Preview Player Position"),
                CommandItem(id: 3172, name: "Consolidate"),
                CommandItem(id: 2179, name: "Unload Preview Player"),
                CommandItem(id: 2798, name: "Analyze Loaded Track"),
                CommandItem(id: 3048, name: "Send Monitor State"),
            ]),
            CommandCategory2(name: "Cruise Mode", commands: [
                CommandItem(id: 8194, name: "Cruise Mode On"),
                CommandItem(id: 8195, name: "Cruise Mode Skip"),
                CommandItem(id: 8196, name: "Cruise Mode Shuffle"),
            ]),
        ]),

        // Modifier
        CommandCategory2(name: "Modifier", commands: [
            CommandItem(id: 2548, name: "Modifier #1"),
            CommandItem(id: 2549, name: "Modifier #2"),
            CommandItem(id: 2550, name: "Modifier #3"),
            CommandItem(id: 2551, name: "Modifier #4"),
            CommandItem(id: 2552, name: "Modifier #5"),
            CommandItem(id: 2553, name: "Modifier #6"),
            CommandItem(id: 2554, name: "Modifier #7"),
            CommandItem(id: 2555, name: "Modifier #8"),
        ]),

        // Microphone
        CommandCategory2(name: "Microphone", commands: [
            CommandItem(id: 295, name: "Microphone Gain"),
            CommandItem(id: 296, name: "Microphone On"),
        ]),
    ]
}
